// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_MDP_Web.Data;

#nullable disable

namespace Proiect_MDP_Web.Migrations
{
    [DbContext(typeof(Proiect_MDP_WebContext))]
    [Migration("20240110181851_Recenzie")]
    partial class Recenzie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proiect_MDP_Web.Models.Categorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.CategorieRacheta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.Property<int>("RachetaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategorieID");

                    b.HasIndex("RachetaID");

                    b.ToTable("CategorieRacheta");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adresa")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prenume")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Firma", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireFirma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locatie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Firma");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Magazin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireMagazin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Magazin");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Racheta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DimensiuneCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("Editie")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("Greutate")
                        .HasColumnType("int");

                    b.Property<int?>("MagazinID")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Tehnologie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FirmaID");

                    b.HasIndex("MagazinID");

                    b.ToTable("Racheta");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Serviciu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<int?>("RachetaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipServiciu")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("RachetaID");

                    b.ToTable("Serviciu");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.CategorieRacheta", b =>
                {
                    b.HasOne("Proiect_MDP_Web.Models.Categorie", "Categorie")
                        .WithMany("CategoriiRacheta")
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_MDP_Web.Models.Racheta", "Racheta")
                        .WithMany("CategoriiRacheta")
                        .HasForeignKey("RachetaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Racheta");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Racheta", b =>
                {
                    b.HasOne("Proiect_MDP_Web.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaID");

                    b.HasOne("Proiect_MDP_Web.Models.Magazin", "Magazin")
                        .WithMany("Rachete")
                        .HasForeignKey("MagazinID");

                    b.Navigation("Firma");

                    b.Navigation("Magazin");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Serviciu", b =>
                {
                    b.HasOne("Proiect_MDP_Web.Models.Client", "Client")
                        .WithMany("Servicii")
                        .HasForeignKey("ClientID");

                    b.HasOne("Proiect_MDP_Web.Models.Racheta", "Racheta")
                        .WithMany()
                        .HasForeignKey("RachetaID");

                    b.Navigation("Client");

                    b.Navigation("Racheta");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Categorie", b =>
                {
                    b.Navigation("CategoriiRacheta");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Client", b =>
                {
                    b.Navigation("Servicii");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Magazin", b =>
                {
                    b.Navigation("Rachete");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Racheta", b =>
                {
                    b.Navigation("CategoriiRacheta");
                });
#pragma warning restore 612, 618
        }
    }
}
