// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_MDP_Web.Data;

#nullable disable

namespace Proiect_MDP_Web.Migrations
{
    [DbContext(typeof(Proiect_MDP_WebContext))]
    [Migration("20240102160937_CreateMagazin")]
    partial class CreateMagazin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proiect_MDP_Web.Models.Magazin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireMagazin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Magazin");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Racheta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DimensiuneCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("Editie")
                        .HasColumnType("datetime2");

                    b.Property<int>("Greutate")
                        .HasColumnType("int");

                    b.Property<int?>("MagazinID")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Tehnologie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MagazinID");

                    b.ToTable("Racheta");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Racheta", b =>
                {
                    b.HasOne("Proiect_MDP_Web.Models.Magazin", "Magazin")
                        .WithMany("Rachete")
                        .HasForeignKey("MagazinID");

                    b.Navigation("Magazin");
                });

            modelBuilder.Entity("Proiect_MDP_Web.Models.Magazin", b =>
                {
                    b.Navigation("Rachete");
                });
#pragma warning restore 612, 618
        }
    }
}
